/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPenjualan;

import AplikasiPenjualan.MenuUtama;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author YOGI
 */
public class Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan
     */
    PenjualanModel penjualanModel = new PenjualanModel();
    public Penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldKode = new javax.swing.JTextField();
        fieldHarga = new javax.swing.JTextField();
        fieldTotal = new javax.swing.JTextField();
        fieldPtg = new javax.swing.JTextField();
        fieldPayment = new javax.swing.JTextField();
        fieldKembali = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        fieldJumlah = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTransaksi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldKode.setBorder(null);
        getContentPane().add(fieldKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 20));

        fieldHarga.setBorder(null);
        getContentPane().add(fieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, -1));

        fieldTotal.setBorder(null);
        getContentPane().add(fieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 80, 20));

        fieldPtg.setBorder(null);
        fieldPtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPtgActionPerformed(evt);
            }
        });
        getContentPane().add(fieldPtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, 20));

        fieldPayment.setBorder(null);
        getContentPane().add(fieldPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 244, 50, -1));

        fieldKembali.setBorder(null);
        getContentPane().add(fieldKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 80, 20));

        fieldNama.setBorder(null);
        getContentPane().add(fieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, 20));

        fieldJumlah.setBorder(null);
        getContentPane().add(fieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/dataTransaksiBackButton.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, 50));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/dataTransaksiCalculateButton.png"))); // NOI18N
        btnSubmit.setBorderPainted(false);
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, -1));

        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/dataTransaksiPayButton.png"))); // NOI18N
        btnPayment.setBorderPainted(false);
        btnPayment.setContentAreaFilled(false);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 60, -1));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/dataTransaksiResetButton.png"))); // NOI18N
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 90, 30));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/dataTransaksiDeleteButton.png"))); // NOI18N
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 70, -1));

        dataTransaksi.setModel(penjualanModel.modelTransaksi);
        penjualanModel.setupTableTransaksi();
        jScrollPane1.setViewportView(dataTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 620, 50));

        dataTable.setModel(PenjualanModel.model);
        penjualanModel.setupTable();
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dataTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 620, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramPenjualan/transaksi.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPtgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPtgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuUtama().setVisible(true);
        PenjualanModel.model.setColumnCount(0);
        PenjualanModel.model.setRowCount(0);
        PenjualanModel.modelTransaksi.setColumnCount(0);
        PenjualanModel.modelTransaksi.setRowCount(0);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        int getRow = dataTable.rowAtPoint(evt.getPoint());
        String kdBarang = dataTable.getValueAt(getRow, 0).toString();
        fieldKode.setText(kdBarang);
        
        String namaBarang = dataTable.getValueAt(getRow, 1).toString();
        fieldNama.setText(namaBarang);
        
        String hrgBeli = dataTable.getValueAt(getRow, 4).toString();
        fieldHarga.setText(hrgBeli);
    }//GEN-LAST:event_dataTableMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int getRow = dataTable.getSelectedRow();
        int jumlahBarang = (int) dataTable.getValueAt(getRow, 2);
        int harga = Integer.parseInt(fieldHarga.getText());
        int jumlah = (int) fieldJumlah.getValue();
        
        if(jumlah > jumlahBarang ) {
            JOptionPane.showMessageDialog(null, "Jumlah melebihi jumlah barang yang tersedia");
        } else {
            int hasil = (harga*jumlah);
            if(hasil > 100000) {
                int potongan = (int) ((int) hasil * 0.2);
                fieldPtg.setText(Integer.toString(potongan));
                int hasilAkhir = hasil - potongan;
                fieldTotal.setText(Integer.toString(hasilAkhir));
            } else {
                fieldTotal.setText(Integer.toString(hasil));
                fieldPtg.setText("0");
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        int total = Integer.parseInt(fieldTotal.getText());
        int bayar = Integer.parseInt(fieldPayment.getText());
        if(bayar < total) {
            JOptionPane.showMessageDialog(null, "Uang anda tidak cukup!");
        } else {
            int kembali = bayar - total;
            fieldKembali.setText(Integer.toString(kembali));
        }
        
        String kodeBarang = fieldKode.getText();
        int hargaBarang = Integer.parseInt(fieldHarga.getText());
        int jumlah =(int) fieldJumlah.getValue();
        int potongan = Integer.parseInt(fieldPtg.getText());
        int totalHrg = Integer.parseInt(fieldTotal.getText());
        
        penjualanModel.decrement(jumlah, kodeBarang);
        penjualanModel.insertData(kodeBarang, hargaBarang, jumlah, potongan, totalHrg);
        reload();
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        penjualanModel.deleteAllData();
        reload();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int getRow = dataTransaksi.getSelectedRow();
        String kodeBarang = dataTransaksi.getValueAt(getRow, 0).toString();
        String jumlah = dataTransaksi.getValueAt(getRow, 2).toString();
        
        penjualanModel.deleteData(kodeBarang, jumlah);
        reload();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }
    
    public void reload() {
        PenjualanModel.model.setColumnCount(0);
        PenjualanModel.model.setRowCount(0);
        PenjualanModel.modelTransaksi.setColumnCount(0);
        PenjualanModel.modelTransaksi.setRowCount(0);
        penjualanModel.setupTable();
        penjualanModel.setupTableTransaksi();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTable dataTable;
    private javax.swing.JTable dataTransaksi;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JSpinner fieldJumlah;
    private javax.swing.JTextField fieldKembali;
    private javax.swing.JTextField fieldKode;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldPayment;
    private javax.swing.JTextField fieldPtg;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
